version: '3.8'

services:
    nginx:
        build:
            context: phone.book
            target: nginx
        container_name: nginx-container
        ports:
            - '80:80'
        volumes:
            - ./:/home/www-data/phone.book
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - edu-report-network
        depends_on:
            - php

    php:
        build:
            context: phone.book
            target: php
            args:
                USER_UID: ${USER_UID}
        container_name: php-container
        volumes:
            - ./:/home/www-data/phone.book
        networks:
            - edu-report-network
        depends_on:
            - mysql

    mysql:
        build:
            context: phone.book
            target: mysql
        container_name: mysql-container
        restart: always
        ports:
            - '3306:3306'
        command:
          ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            edu-report-network:
                aliases:
                    - mysql

networks:
    edu-report-network:
        driver: bridge